apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: nalej
#  annotations:
#    external-dns.alpha.kubernetes.io/hostname: coredns.nalej.tech
  labels:
    app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    app: coredns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  type: LoadBalancer