apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: __NPH_NAMESPACE
  labels:
    cluster: management
    component: external-dns
spec:
  selector:
    matchLabels:
      cluster: management
      component: external-dns
  template:
    metadata:
      labels:
        cluster: management
        component: external-dns
    spec:
      containers:
      - name: coredns
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/coredns:__NPH_VERSION
        imagePullPolicy: Always
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
      imagePullSecrets:
        - name: nalej-registry
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
