apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: __NPH_NAMESPACE
data:
  Corefile: |
    .:53 {
      corednsnalejplugin {
        systemModelAddress system-model.__NPH_NAMESPACE:8800
      }
    }
